# Generated by Django 2.1 on 2018-09-02 08:10

from django.db import migrations, models
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    """ create superuser
    default username: admin
    default password: adminadmin

    refer: https://gist.github.com/inirudebwoy/7eb2d74ea950c38559e5
    """
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.com'
    superuser.set_password('adminadmin')
    superuser.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
                ('note', models.TextField(blank=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_superuser),
    ]
